import type {
  DashboardStats,
  Workflow,
  Execution,
  Incident,
  N8nInstance,
  Alert,
} from "@/types";

export const mockInstance: N8nInstance = {
  id: "inst_01",
  org_id: "org_demo",
  name: "Production",
  url: "https://n8n.mycompany.com",
  api_key_hint: "••••4f2a",
  is_active: true,
  last_synced_at: new Date(Date.now() - 45000).toISOString(),
  created_at: "2024-10-01T00:00:00Z",
};

export const mockInstances: N8nInstance[] = [
  mockInstance,
  {
    id: "inst_02",
    org_id: "org_demo",
    name: "Staging",
    url: "https://n8n-staging.mycompany.com",
    api_key_hint: "••••9c1b",
    is_active: true,
    last_synced_at: new Date(Date.now() - 120000).toISOString(),
    created_at: "2024-11-15T00:00:00Z",
  },
];

// ─── Dashboard Stats ──────────────────────────────────────────────────────────

function generateTrend(hours = 24) {
  const now = Date.now();
  return Array.from({ length: hours }, (_, i) => {
    const base = 80 + Math.floor(Math.random() * 60);
    const failures = Math.floor(Math.random() * 8);
    return {
      time: new Date(now - (hours - i) * 3600000).toISOString(),
      executions: base,
      failures,
    };
  });
}

export const mockStats: DashboardStats = {
  total_workflows: 47,
  active_workflows: 38,
  executions_24h: 2341,
  failures_24h: 14,
  success_rate: 99.4,
  avg_duration_ms: 3240,
  open_incidents: 2,
  executions_trend: generateTrend(24),
  failures_trend: generateTrend(24),
};

// ─── Workflows ────────────────────────────────────────────────────────────────

export const mockWorkflows: Workflow[] = [
  {
    id: "wf_01",
    instance_id: "inst_01",
    n8n_id: "1",
    name: "Lead Enrichment → CRM Sync",
    status: "active",
    tags: ["crm", "leads"],
    node_count: 12,
    last_execution_at: new Date(Date.now() - 180000).toISOString(),
    last_execution_status: "success",
    executions_24h: 348,
    failures_24h: 0,
    success_rate: 100,
    avg_duration_ms: 1850,
    created_at: "2024-10-05T00:00:00Z",
    updated_at: "2025-03-12T00:00:00Z",
  },
  {
    id: "wf_02",
    instance_id: "inst_01",
    n8n_id: "2",
    name: "Stripe Payment → Invoice Generator",
    status: "active",
    tags: ["billing", "stripe"],
    node_count: 8,
    last_execution_at: new Date(Date.now() - 600000).toISOString(),
    last_execution_status: "error",
    executions_24h: 124,
    failures_24h: 7,
    success_rate: 94.4,
    avg_duration_ms: 2200,
    created_at: "2024-10-08T00:00:00Z",
    updated_at: "2025-04-01T00:00:00Z",
  },
  {
    id: "wf_03",
    instance_id: "inst_01",
    n8n_id: "3",
    name: "Slack Alerts → Incident Router",
    status: "active",
    tags: ["alerts", "ops"],
    node_count: 6,
    last_execution_at: new Date(Date.now() - 30000).toISOString(),
    last_execution_status: "success",
    executions_24h: 892,
    failures_24h: 2,
    success_rate: 99.8,
    avg_duration_ms: 420,
    created_at: "2024-11-01T00:00:00Z",
    updated_at: "2025-03-20T00:00:00Z",
  },
  {
    id: "wf_04",
    instance_id: "inst_01",
    n8n_id: "4",
    name: "Daily Report Builder",
    status: "active",
    tags: ["reports", "scheduled"],
    node_count: 15,
    last_execution_at: new Date(Date.now() - 86400000).toISOString(),
    last_execution_status: "success",
    executions_24h: 1,
    failures_24h: 0,
    success_rate: 98.2,
    avg_duration_ms: 12400,
    created_at: "2024-09-20T00:00:00Z",
    updated_at: "2025-02-14T00:00:00Z",
  },
  {
    id: "wf_05",
    instance_id: "inst_01",
    n8n_id: "5",
    name: "Email Sequence Trigger",
    status: "active",
    tags: ["email", "marketing"],
    node_count: 9,
    last_execution_at: new Date(Date.now() - 3600000).toISOString(),
    last_execution_status: "success",
    executions_24h: 567,
    failures_24h: 3,
    success_rate: 99.5,
    avg_duration_ms: 980,
    created_at: "2024-10-15T00:00:00Z",
    updated_at: "2025-03-30T00:00:00Z",
  },
  {
    id: "wf_06",
    instance_id: "inst_01",
    n8n_id: "6",
    name: "Webhook → Database Sync",
    status: "inactive",
    tags: ["database"],
    node_count: 5,
    last_execution_at: new Date(Date.now() - 172800000).toISOString(),
    last_execution_status: "success",
    executions_24h: 0,
    failures_24h: 0,
    success_rate: 97.1,
    avg_duration_ms: 650,
    created_at: "2024-08-10T00:00:00Z",
    updated_at: "2025-01-05T00:00:00Z",
  },
];

// ─── Executions ───────────────────────────────────────────────────────────────

export const mockExecutions: Execution[] = [
  {
    id: "ex_01",
    instance_id: "inst_01",
    workflow_id: "wf_02",
    workflow_name: "Stripe Payment → Invoice Generator",
    n8n_execution_id: "9842",
    status: "error",
    started_at: new Date(Date.now() - 600000).toISOString(),
    finished_at: new Date(Date.now() - 597000).toISOString(),
    duration_ms: 3100,
    failed_node: "Generate PDF",
    error_message: "Error: Cannot read properties of undefined (reading 'amount'). The Stripe webhook payload is missing the 'amount' field — likely a new payment type not yet handled.",
    error_type: "TypeError",
    mode: "webhook",
    data: {
      nodes: [
        { name: "Stripe Webhook", type: "n8n-nodes-base.webhook", status: "success", duration_ms: 12 },
        { name: "Validate Payload", type: "n8n-nodes-base.code", status: "success", duration_ms: 48 },
        { name: "Fetch Customer", type: "n8n-nodes-base.httpRequest", status: "success", duration_ms: 340 },
        { name: "Generate PDF", type: "n8n-nodes-base.code", status: "error", duration_ms: 2700, error: "Cannot read properties of undefined (reading 'amount')" },
        { name: "Send Invoice Email", type: "n8n-nodes-base.emailSend", status: "skipped", duration_ms: 0 },
      ],
    },
  },
  {
    id: "ex_02",
    instance_id: "inst_01",
    workflow_id: "wf_01",
    workflow_name: "Lead Enrichment → CRM Sync",
    n8n_execution_id: "9841",
    status: "success",
    started_at: new Date(Date.now() - 720000).toISOString(),
    finished_at: new Date(Date.now() - 718200).toISOString(),
    duration_ms: 1800,
    failed_node: null,
    error_message: null,
    error_type: null,
    mode: "trigger",
  },
  {
    id: "ex_03",
    instance_id: "inst_01",
    workflow_id: "wf_03",
    workflow_name: "Slack Alerts → Incident Router",
    n8n_execution_id: "9840",
    status: "success",
    started_at: new Date(Date.now() - 900000).toISOString(),
    finished_at: new Date(Date.now() - 899580).toISOString(),
    duration_ms: 420,
    failed_node: null,
    error_message: null,
    error_type: null,
    mode: "webhook",
  },
  {
    id: "ex_04",
    instance_id: "inst_01",
    workflow_id: "wf_02",
    workflow_name: "Stripe Payment → Invoice Generator",
    n8n_execution_id: "9835",
    status: "error",
    started_at: new Date(Date.now() - 3600000).toISOString(),
    finished_at: new Date(Date.now() - 3596900).toISOString(),
    duration_ms: 3100,
    failed_node: "Generate PDF",
    error_message: "Cannot read properties of undefined (reading 'amount')",
    error_type: "TypeError",
    mode: "webhook",
  },
  {
    id: "ex_05",
    instance_id: "inst_01",
    workflow_id: "wf_05",
    workflow_name: "Email Sequence Trigger",
    n8n_execution_id: "9828",
    status: "success",
    started_at: new Date(Date.now() - 7200000).toISOString(),
    finished_at: new Date(Date.now() - 7199020).toISOString(),
    duration_ms: 980,
    failed_node: null,
    error_message: null,
    error_type: null,
    mode: "trigger",
  },
];

// ─── Incidents ────────────────────────────────────────────────────────────────

export const mockIncidents: Incident[] = [
  {
    id: "inc_01",
    instance_id: "inst_01",
    workflow_id: "wf_02",
    n8n_workflow_id: "wf_02",
    workflow_name: "Stripe Payment → Invoice Generator",
    severity: "high",
    status: "open",
    title: "Recurring TypeError in Generate PDF node",
    failure_count: 7,
    first_seen_at: new Date(Date.now() - 7200000).toISOString(),
    last_seen_at: new Date(Date.now() - 600000).toISOString(),
    resolved_at: null,
    assigned_to: null,
    last_n8n_execution_id: null,
    error_signature: null,
    node_name: "Generate PDF",
    error_message: "TypeError: Cannot read properties of undefined (reading 'invoiceId')",
  },
  {
    id: "inc_02",
    instance_id: "inst_01",
    workflow_id: "wf_03",
    n8n_workflow_id: "wf_03",
    workflow_name: "Slack Alerts → Incident Router",
    severity: "low",
    status: "investigating",
    title: "Occasional timeout on Slack API call",
    failure_count: 2,
    first_seen_at: new Date(Date.now() - 14400000).toISOString(),
    last_seen_at: new Date(Date.now() - 3600000).toISOString(),
    resolved_at: null,
    assigned_to: "user_01",
    last_n8n_execution_id: null,
    error_signature: null,
    node_name: "Slack",
    error_message: "Request timed out after 30000ms",
  },
  {
    id: "inc_03",
    instance_id: "inst_01",
    workflow_id: "wf_05",
    n8n_workflow_id: "wf_05",
    workflow_name: "Email Sequence Trigger",
    severity: "medium",
    status: "resolved",
    title: "SMTP connection refused intermittently",
    failure_count: 5,
    first_seen_at: new Date(Date.now() - 172800000).toISOString(),
    last_seen_at: new Date(Date.now() - 86400000).toISOString(),
    resolved_at: new Date(Date.now() - 82800000).toISOString(),
    assigned_to: "user_01",
    last_n8n_execution_id: null,
    error_signature: null,
    node_name: "Send Email",
    error_message: "connect ECONNREFUSED 127.0.0.1:587",
  },
];

// ─── Alerts ───────────────────────────────────────────────────────────────────

export const mockAlerts: Alert[] = [
  {
    id: "alert_01",
    instance_id: "inst_01",
    workflow_id: "wf_02",
    name: "Stripe Invoice Failures",
    channel: "slack",
    destination: "#incidents",
    threshold_count: 3,
    threshold_minutes: 10,
    cooldown_minutes: 30,
    is_active: true,
    created_at: "2024-10-10T00:00:00Z",
  },
  {
    id: "alert_02",
    instance_id: "inst_01",
    workflow_id: null,
    name: "Any Workflow Failure",
    channel: "email",
    destination: "ops@mycompany.com",
    threshold_count: 5,
    threshold_minutes: 15,
    cooldown_minutes: 60,
    is_active: true,
    created_at: "2024-10-01T00:00:00Z",
  },
  {
    id: "alert_03",
    instance_id: "inst_01",
    workflow_id: "wf_03",
    name: "Slack Router Timeout Alert",
    channel: "webhook",
    destination: "https://hooks.mycompany.com/alerts",
    threshold_count: 2,
    threshold_minutes: 5,
    cooldown_minutes: 15,
    is_active: false,
    created_at: "2024-11-05T00:00:00Z",
  },
  {
    id: "alert_04",
    instance_id: "inst_01",
    workflow_id: null,
    name: "High Failure Rate",
    channel: "slack",
    destination: "#ops-critical",
    threshold_count: 10,
    threshold_minutes: 30,
    cooldown_minutes: 120,
    is_active: true,
    created_at: "2025-01-15T00:00:00Z",
  },
];
